### ISSUE TITLE
Support for compressed jpeg output

### ISSUE THREAD

**Issue by LI7XI** [bfraboni/FastGaussianBlur#1]
Is there a room for implementing image compression?

a 62Kb jpg image after blur becomes a 419Kb png with 50 sigma.
But after using compression (i used [Caesium](https://github.com/Lymphatus/caesium-image-compressor)) the size dropped to just 28Kb, using lossy jpg with 80 quality.
I also tried using cjpeg but it doesn't seem to accept png on windows.

Any thoughts about this?
Thanks!

**Comment by bfraboni** [comment]
Hum I choose .PNG output as default, but std_image_write can also write .JPG using the `stbi_write_jpg` function:
https://github.com/bfraboni/FastGaussianBlur/blob/2ff073fbc3ae2529bfc261d145f29b379af6738b/stb_image_write.h#L50

A cleaner version would be to detect the desired extension from the `output_file_name` argument and use the adequate stbi write function or return an error if the file format is not supported.

For now I suggest you modify the write function by hand and specify .JPG output file so you can  directly have jpg images !

**Comment by bfraboni** [comment]
Ok It was simple enough to make a fix at lunch, you can now specify .jpg / .bmp / .png in output_file, which is automatically detected at save. Any other extension will fall to default png with a warning. 
The associated commit: 
https://github.com/bfraboni/FastGaussianBlur/commit/b4ebbfdfd4f62b70b881b64650af11fccad07901

**Comment by LI7XI** [comment]
Thanks a ton!
Worked perfectly ;)
