### ISSUE TITLE
Exception: Access violation reading

### ISSUE THREAD

**Issue by windowsair** [bfraboni/FastGaussianBlur#3]
reproduce command:

```bash
./fastblur test12.png out.png 250
```
[test12.zip](https://github.com/bfraboni/FastGaussianBlur/files/8761723/test12.zip)

I'm not sure if it's a issue about sigma, but on OpenCV, everything works fine for the Gaussian calculation.

**Comment by bfraboni** [comment]
Okay that's expected with the current implementation, I assumed reasonable sigmas regarding the size of the input buffer, and forgot to check for too large values or to clamp the kernel to something feasible when values are too large.

Your input image resolution is 500x350, and an isotropic gaussian of std dev 250 have an approximate kernel support of resolution 643x643 which is superior to your input resolution. So in this situation OpenCV clamps the kernel support for Gaussian Blur. So I'll have to do the same for the box kernel of the Fast Gaussian Blur.

I'll try to fix soon.

**Comment by bfraboni** [comment]
Fixed in commit : https://github.com/bfraboni/FastGaussianBlur/commit/5d4207b44a4be4118592228d7f6a7dfa53bed384
Arbitrary sigmas can be specified without error.

**Comment by windowsair** [comment]
Amazing work! Thank you!



------------------ Original ------------------
From: Basile Fraboni ***@***.***&gt;
Date: Fri,May 27,2022 6:13 PM
To: bfraboni/FastGaussianBlur ***@***.***&gt;
Cc: windowsair ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [bfraboni/FastGaussianBlur] Exception: Access violation reading (Issue #3)





 
Closed #3 as completed.
