### ISSUE TITLE
output is a slighty darker when using uchar arrays due to non rounded multiply

### ISSUE THREAD

**Issue by michelerenzullo** [bfraboni/FastGaussianBlur#4]
when you multiply the output with float "iarr" and "T" is uchar you should add +0.5f to round it, otherwise the output will be slighty darker, I suggest to add a constexpr to check if T is uchar and so round it, if you do that the output is as expected to be.

https://github.com/bfraboni/FastGaussianBlur/blob/fabc47f62a53a201e685a78e15320aba6e341cfd/fast_gaussian_blur_template.h#L99

GOOD - opencv blur as reference:
![opencv_blur](https://user-images.githubusercontent.com/76132686/189514828-42cf5ca4-c291-451b-9827-08f3cee5f581.png)
GOOD - Uchar rounded:
![FGB_uchar_rounded](https://user-images.githubusercontent.com/76132686/189514825-0144307d-a098-41b7-bed9-c48ff82023d3.png)
BAD - Uchar not rounded
![FGB_uchar](https://user-images.githubusercontent.com/76132686/189514830-44d8ed2c-3ef2-42bc-a88e-7073204bd969.png)

**Comment by bfraboni** [comment]
Thank you for noticing this.
I've run into integer rounding issues before, and had fixed the problem in the code at one point, but it was lost in subsequent changes.
The latest commit solves the problem for the two exposed border policies and for any integral type:

https://github.com/bfraboni/FastGaussianBlur/blob/05508f89bd9ad1ed75ade49fb71e5cae75b53f94/fast_gaussian_blur_template.h#L99

https://github.com/bfraboni/FastGaussianBlur/blob/05508f89bd9ad1ed75ade49fb71e5cae75b53f94/fast_gaussian_blur_template.h#L146

Let me know if it fits your needs before I close the issue.

**Comment by michelerenzullo** [comment]
That's should be perfect, what I thought, dealing with uchar or uint16_t or any integral...  I will try in a bit thanks
