### ISSUE TITLE
performance improvement on big images

### ISSUE THREAD

**Issue by michelerenzullo** [bfraboni/FastGaussianBlur#5]
Integer mul is usually faster than float one, so when T is uchar(or any other integer) we don't need to use float, this increase the performance, tested on an old laptop, using an image 24bit 6000 * 8000 px and r = 337
You might add a check for the type T, using float or int based on him. Let me know

https://github.com/bfraboni/FastGaussianBlur/blob/05508f89bd9ad1ed75ade49fb71e5cae75b53f94/fast_gaussian_blur_template.h#L77

with float
(horizontalblur only, tot - transp) : 4120.961600
(horizontalblur only, tot - transp) : 4184.653200
(horizontalblur only, tot - transp) : 4241.367500
(horizontalblur only, tot - transp) : 4068.939800

with int
(horizontalblur only, tot - transp) : 3496.743000
(horizontalblur only, tot - transp) : 3719.186500
(horizontalblur only, tot - transp) : 3510.837400
(horizontalblur only, tot - transp) : 3603.649300

**Comment by bfraboni** [comment]
Thanks for noticing this.
Again, I checked in the first commit 84e5f2db75af3da8b9068c7f551e88feec67d5fb and at this time the value type was conditioned by the template type as follows:

https://github.com/bfraboni/FastGaussianBlur/blob/84e5f2db75af3da8b9068c7f551e88feec67d5fb/fast_gaussian_blur_template.h#L18

I don't know why I dropped it at some point, but I think I'll get back to this solution, even though it is not super readable. 
Maybe a version with a typedef or a using could be less obfuscated.
I'll try later in the day to check the timings and do a proper commit to fix it.

**Comment by bfraboni** [comment]
I think the last commit do the job.
I get 100ms improvement on integer VS floating point calculations on my 2016 laptop for a 8k * 4k image. 
Did not check on my desktop computer though. 
Let me know if its ok on your side before I close the issue.

**Comment by michelerenzullo** [comment]
I will run the previous test again and it should do the good job, since it will deduce the type from template. I'm using a very old laptop because mine is in warranty, so any little improvements is exponential on mine. Nice

**Comment by michelerenzullo** [comment]
confirmed, it works, -700ms with 6000x8000px , I close
